# Generated by Django 4.0.3 on 2022-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Project name', max_length=70, verbose_name='Project name')),
                ('anons', models.CharField(default='About project', max_length=250, verbose_name='About project')),
                ('full_text', models.TextField(verbose_name='Project')),
                ('img', models.ImageField(height_field=300, upload_to='', width_field=300)),
                ('date', models.DateTimeField(verbose_name='Publish date')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
